version: '3'
services:
  py39:
    image: srittau/wsgi-base:3.9
    build:
      context: .
      args:
        - pyversion=3.9
  py38:
    image: srittau/wsgi-base:3.8
    build:
      context: .
      args:
        - pyversion=3.8
  latest:
    image: srittau/wsgi-base:latest
    build: .
