version: '3'
services:
  py310:
    image: srittau/wsgi-base:3.10
    build:
      context: .
      args:
        - pyversion=3.10
  py39:
    image: srittau/wsgi-base:3.9
    build:
      context: .
      args:
        - pyversion=3.9
  latest:
    image: srittau/wsgi-base:latest
    build: .
